### PR TITLE
Fix wheel build

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by gbarkadiusz** [comment]
We need this fix as fast as possible. @huffman  Could you merge this pr and release 1.0.7 version.?

**Comment by gbarkadiusz** [comment]
So far I investigated that pip install <package_name> doesn't work instead of this way.
```
git clone https://github.com/saleae/logic2-automation
cd logic2-automation/python && pip install .
```

**Comment by ofek** [comment]
Change this https://github.com/saleae/logic2-automation/blob/b6468259c696a67168df5d5b3162afb8d3d07c6d/python/pyproject.toml#L43

to this:

```toml
[tool.hatch.build.targets.sdist.force-include]
```

**Comment by huffman** [comment]
@ofek Thank you!

@gbarkadiusz We'll have a release out shortly.

**Comment by huffman** [comment]
@gbarkadiusz 1.0.7 has been released - please let us know if you have any issue with the upgrade! https://pypi.org/project/logic2-automation/

@ofek Thanks again, I really appreciate the help! I'm sure you saved me an hour of debugging.

**Comment by ofek** [comment]
Happy to help! Also, cool project 🙂

**Comment by ofek** [comment]
FYI here's an explanation: https://github.com/pypa/hatch/issues/1130#issuecomment-1853296562

**Comment by gbarkadiusz** [comment]
@huffman Thank you for that quick investigation and fix. It works properly with my CI.

**Pull request closed without merging**
